name: theme_tailor_annotation
description: >
  Annotations for the Theme Tailor code-generator.
  This package does nothing without Theme Tailor.
version: 2.0.0
repository: https://github.com/Iteo/theme_tailor
issue_tracker: https://github.com/Iteo/theme_tailor/issues
homepage: https://github.com/Iteo/theme_tailor
documentation: https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/README.md

environment:
  sdk: ^3.2.0
  flutter: 3.19.6

dependencies:
  collection: 1.18.0
  json_annotation: 4.8.1
  meta: 1.11.0

dev_dependencies:
  build_runner: 2.4.6
  json_serializable: 6.7.1
