name: theme_tailor
description: >
  Code generator for Flutter's 3.0 ThemeExtension classes. 
  The generator can create themes and extensions on BuildContext 
  or ThemeData based on the lists of the theme properties
version: 2.0.0
publish_to: none

environment:
  sdk: 3.0.5
  flutter: 3.10.5

dependencies:
  analyzer: 5.13.0
  build_config: 1.1.1
  build: 2.4.0
  collection: 1.17.1
  json_annotation: 4.8.1
  meta: 1.9.1 
  source_gen_test: 1.0.5
  source_gen: 1.3.2
  source_helper: 1.3.3
  theme_tailor_annotation: 
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor_annotation
  
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.3

screenshots:
  - description: Package logo
    path: screenshots/logo.png
