name: theme_tailor
description: >
  Code generator for Flutter's 3.0 ThemeExtension classes. 
  The generator can create themes and extensions on BuildContext 
  or ThemeData based on the lists of the theme properties
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: 3.22.2

dependencies:
  analyzer: 6.2.0
  build_config: 1.1.1
  build: 2.4.1
  collection: 1.18.0
  json_annotation: 4.9.0
  meta: 1.12.0
  source_gen_test: 1.0.6
  source_gen: 1.4.0
  source_helper: 1.3.4
  theme_tailor_annotation:
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor_annotation

dev_dependencies:
  lints: 3.0.0
  test: 1.24.9

screenshots:
  - description: Package logo
    path: screenshots/logo.png
