name: theme_tailor_toolbox
description: >
  Theming utilities and additional annotations for ThemeTailor code generator
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.9.0
  theme_tailor_annotation: 2.0.2

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
